name: love_choice
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^11.0.0
  url_launcher: ^6.3.2
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.6
  d_dialog: ^1.0.2
  shared_preferences: ^2.5.3
  http: ^1.4.0
  lottie: ^3.3.1
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  flutter_local_notifications: ^19.4.0
  fluttertoast: ^8.2.12
  redacted: ^1.0.13
  smooth_page_indicator: ^1.2.1
  permission_handler: ^12.0.1
  android_intent_plus: ^5.3.1
  device_info_plus: ^11.5.0
  supabase_flutter: ^2.0.0
  image_picker: ^1.1.0
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/love_choice.db
    - assets/animation/
    - .env
  
  fonts:
    - family: TurkLogo
      fonts:
        - asset: fonts/logo.ttf
    - family: TurkFont
      fonts:
        - asset: fonts/arabic_font.otf
    - family: TurkD
      fonts:
        - asset: fonts/dewan.ttf
    - family: TurkFontE
      fonts:
        - asset: fonts/Winter_Farmhouse.otf